### ISSUE TITLE
Invalid Parameter - 100

### ISSUE THREAD

**Issue by VaclovasV** [tacoss/dayguard#3]
I keep getting this error:

> Running:  Take an screenshot and ask for differences
>  ✖ Error: Command failed: Invalid Parameter - 100
> 
>     at maybeClose (internal/child_process.js:852:16)
>     at Socket.<anonymous> (internal/child_process.js:323:11)
>     at Pipe._handle.close [as _onclose] (net.js:492:12)
> 
> FAILED:  1 errors (485ms)
> 
>  _________________________________________________
> 
>  TEST FAILURE: 1 error during execution,  0 assertions failed, 1 passed. (4.193s)

**Comment by straris** [comment]
Hey @VaclovasV do you have a test that reproduces the issue?
I'm able to run the example test fine.

**Comment by VaclovasV** [comment]
@straris test is the same as in example, tried to change url, but still - the same.

**Comment by pateketrueke** [comment]
@VaclovasV which node version you're using?

Please share your specs in order to understand more your problem.

Thanks for your feedback!

**Comment by VaclovasV** [comment]
6.4

**Comment by pateketrueke** [comment]
Could provide more information?

The whole log is also very useful. 🤔

**Comment by VaclovasV** [comment]
What other information do you need?

> Starting selenium server... started - PID:  10360
> 
> [Dayguard] Test Suite
> =========================
> 
> Running:  Load an example page just for testing
>  √ Element <body> was visible after 57 milliseconds.
> 
> OK. 1 assertions passed. (5.27s)
> 
> Running:  Take an screenshot and ask for differences
>  ✖ Error: Command failed: Invalid Parameter - 100
> 
>     at maybeClose (internal/child_process.js:852:16)
>     at Socket.<anonymous> (internal/child_process.js:323:11)
>     at Pipe._handle.close [as _onclose] (net.js:492:12)
> 
> FAILED:  1 errors (441ms)
> 
>  _________________________________________________
> 
>  TEST FAILURE: 1 error during execution,  0 assertions failed, 1 passed. (7.699s)
> 
>  × dayguard
> 
>    - Take an screenshot and ask for differences (441ms)
> 
>

**Comment by VaclovasV** [comment]
selenium log:
09:28:18.214 INFO - Launching a standalone Selenium Server
09:28:18.347 INFO - Java: Oracle Corporation 25.121-b13
09:28:18.347 INFO - OS: Windows 8.1 6.3 amd64
09:28:18.347 INFO - v2.47.1, with Core v2.47.1. Built from revision 411b314
09:28:18.409 INFO - Driver class not found: com.opera.core.systems.OperaDriver
09:28:18.409 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
09:28:18.597 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
09:28:18.597 INFO - Selenium Server is up and running
09:28:20.767 INFO - Executing: [new session: Capabilities [{acceptSslCerts=true, name=Dayguard, browserName=chrome, javascriptEnabled=true, platform=ANY}]])
09:28:20.788 INFO - Creating a new session for Capabilities [{acceptSslCerts=true, name=Dayguard, browserName=chrome, javascriptEnabled=true, platform=ANY}]
Starting ChromeDriver 2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41) on port 41067
Only local connections are allowed.
09:28:24.685 INFO - Done: [new session: Capabilities [{acceptSslCerts=true, name=Dayguard, browserName=chrome, javascriptEnabled=true, platform=ANY}]]
09:28:24.708 INFO - Executing: [get: http://randomcolour.com/])
09:28:25.792 INFO - Done: [get: http://randomcolour.com/]
09:28:25.801 INFO - Executing: [find elements: By.cssSelector: body])
09:28:25.824 INFO - Done: [find elements: By.cssSelector: body]
09:28:25.840 INFO - Executing: [is displayed: 0 [[ChromeDriver: chrome on WIN8_1 (cdba9ea225f774d38ff7ed2b453cf9cb)] -> css selector: body]])
09:28:25.855 INFO - Done: [is displayed: 0 [[ChromeDriver: chrome on WIN8_1 (cdba9ea225f774d38ff7ed2b453cf9cb)] -> css selector: body]]
09:28:25.871 INFO - Executing: [execute script: var passedArgs = Array.prototype.slice.call(arguments,0); return function getElementPosition() {
  /* eslint-disable */
  var el = document.querySelector(arguments[0]);
  var rect = el.getBoundingClientRect();

  var ratio = window.devicePixelRatio || 1;

  // hide scrollbar for better diffs
  document.body.style.overflow = 'hidden';

  return {
    height: rect.height * ratio,
    width: rect.width * ratio,
    left: rect.left * ratio,
    top: rect.top * ratio
  };
  /* eslint-enable */
}.apply(window, passedArgs);, [body]])
09:28:25.881 INFO - Done: [execute script: var passedArgs = Array.prototype.slice.call(arguments,0); return function getElementPosition() {
  /* eslint-disable */
  var el = document.querySelector(arguments[0]);
  var rect = el.getBoundingClientRect();

  var ratio = window.devicePixelRatio || 1;

  // hide scrollbar for better diffs
  document.body.style.overflow = 'hidden';

  return {
    height: rect.height * ratio,
    width: rect.width * ratio,
    left: rect.left * ratio,
    top: rect.top * ratio
  };
  /* eslint-enable */
}.apply(window, passedArgs);, [body]]
09:28:25.998 INFO - Executing: [take screenshot])
09:28:26.260 INFO - Done: [take screenshot]
09:28:26.359 INFO - Executing: [delete session: af66a7dd-5356-4b36-8fcd-64322f58481a])

**Comment by pateketrueke** [comment]
Do you have GraphicsMagick/ImageMagick installed?

**Comment by VaclovasV** [comment]
@pateketrueke , is it needed? I installed it and now i get another error:
(xxxxxxxx\tests\dayguard.js:3
:
^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Module._load (module.js:424:3)
    at Function.$load (xxxxxxxx\node_modules\nwrun\lib\spawn.js:57:19)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at new Module ((xxxxxxxx\node_modules\nightwatch\lib\runner\module.js:7:23)

**Comment by pateketrueke** [comment]
Yeah, it is required, the `gm` module depends on them.

Now, you get a syntax error, seems like your file syntax is wrong.

I guess you just copied the example from the README, right? Can you paste it?
